# ZMK Studio config
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_STUDIO_LOCK_ON_DISCONNECT=n

# RGB config
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y

# OLED config (zmk-nice-oled)
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y

# nice-oled left half widgets
CONFIG_NICE_OLED_WIDGET_WPM=y
CONFIG_NICE_OLED_WIDGET_WPM_BONGO_CAT=y
CONFIG_NICE_OLED_WIDGET_HID_INDICATORS=y
CONFIG_ZMK_HID_INDICATORS=y
CONFIG_NICE_OLED_WIDGET_MODIFIERS_INDICATORS=y
CONFIG_NICE_OLED_WIDGET_MODIFIERS_INDICATORS_FIXED=y
CONFIG_NICE_OLED_WIDGET_MODIFIERS_INDICATORS_FIXED_SYMBOL=y
CONFIG_NICE_OLED_WIDGET_MODIFIERS_INDICATORS_FIXED_SYMBOL_MACOS=y
CONFIG_NICE_OLED_WIDGET_MODIFIERS_INDICATORS_FIXED_BOX=y
CONFIG_NICE_OLED_WIDGET_LAYER=y
